const records=window.ARCHIVE_DATA,main=document.querySelector('#main'),dialog=document.querySelector('#search'),q=document.querySelector('#q'),results=document.querySelector('#results');
const facilities=window.FACILITY_DATA;
const categories=[...new Set(records.map(x=>x.category))],tags=[...new Set(records.flatMap(x=>x.tags))].sort((a,b)=>a.localeCompare(b,'ja'));
const card=x=>`<button class="card" data-id="${x.id}"><span class="file-tab">FILE ${String(records.indexOf(x)+1).padStart(3,'0')}</span><img src="${x.image}" alt="${x.title}" loading="lazy"><span class="card-copy"><span class="card-meta"><span>分類 / ${x.category}</span><span>${x.date}</span></span><h3>${x.title}</h3><p>${x.excerpt}</p><span class="card-foot"><span>${x.place}</span><span>詳細を見る →</span></span></span></button>`;
function wire(){document.querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>go('detail/'+e.dataset.id));document.querySelectorAll('[data-route]').forEach(e=>e.onclick=()=>go(e.dataset.route==='archive'?'home':e.dataset.route))}function active(r){document.querySelectorAll('[data-route]').forEach(e=>e.classList.toggle('active',e.dataset.route===r))}function go(r){location.hash=r}function random(){let x=records[Math.floor(Math.random()*records.length)];if(location.hash.endsWith(x.id))x=records[(records.indexOf(x)+1)%records.length];go('detail/'+x.id)}
function home(){active('home');main.innerHTML=`<div class="page home-page"><section class="ledger"><div class="ledger-title">管理記録（自動処理情報）</div><div class="ledger-scroll"><table><thead><tr><th>処理番号</th><th>処理対象</th><th>処理区分</th><th>照合日時</th><th>状態</th></tr></thead><tbody><tr><td>SYS-001</td><td>資料本文索引</td><td>全文照合 / UTF-8</td><td>2026.09.13 03:14</td><td>正常</td></tr><tr><td>IMG-${String(records.length*40).padStart(3,'0')}</td><td>画像参照台帳</td><td>外部参照 / 遅延読込</td><td>2026.09.13 03:12</td><td>継続</td></tr><tr><td>CLS-${String(categories.length).padStart(3,'0')}</td><td>分類語彙表</td><td>重複除外 / 昇順</td><td>2026.09.13 02:48</td><td>正常</td></tr><tr><td>TAG-${String(tags.length).padStart(3,'0')}</td><td>付与語句一覧</td><td>仮名照合 / 未校正</td><td>2026.09.12 23:59</td><td>保留</td></tr></tbody></table></div></section><section><div class="section-head"><div><p class="eyebrow">ALL ENTRIES / ${String(records.length).padStart(3,'0')}</p><h2>記録</h2></div></div><div class="featured home-tiles">${records.map(card).join('')}</div></section></div>`;wire()}
function archive(selected='すべて'){active('archive');const list=selected==='すべて'?records:records.filter(x=>x.category===selected);main.innerHTML=`<div class="page"><p class="eyebrow">ALL RECORDS</p><h1 class="archive-title">記録一覧 <small>${String(list.length).padStart(2,'0')}</small></h1><div class="filter">${['すべて',...categories].map(c=>`<button class="chip ${c===selected?'active':''}" data-filter="${c}">${c}</button>`).join('')}</div><div class="grid">${list.map(card).join('')}</div></div>`;wire();document.querySelectorAll('[data-filter]').forEach(e=>e.onclick=()=>archive(e.dataset.filter))}
function tagPage(){active('tags');main.innerHTML=`<div class="page"><p class="eyebrow">INDEX BY WORDS</p><h1 class="archive-title">タグから探す</h1><p class="lead">場所の種類、光、時間、そこで感じたもの。記録に付けた言葉から横断できます。</p><div class="tag-cloud">${tags.map(t=>`<button class="chip" data-tag="${t}"># ${t} <small>${records.filter(x=>x.tags.includes(t)).length}</small></button>`).join('')}</div><div id="tag-results"></div></div>`;document.querySelectorAll('[data-tag]').forEach(e=>e.onclick=()=>{document.querySelectorAll('[data-tag]').forEach(x=>x.classList.toggle('active',x===e));document.querySelector('#tag-results').innerHTML=`<div class="section-head"><h2># ${e.dataset.tag}</h2></div><div class="grid">${records.filter(x=>x.tags.includes(e.dataset.tag)).map(card).join('')}</div>`;wire()})}
const maps=q=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
const tullys=q=>`https://shop.tullys.co.jp/all?keyword=${encodeURIComponent(q)}`;
const catalog=window.FACILITY_CATALOG;
const tullyItems=facilities.hospitals.map(x=>({prefecture:x[0],city:x[2],name:x[1],type:'',rank:'',note:`${x[3]}。病院利用者、付き添い、職員が利用する院内店舗。`,official:tullys(x[1]),maps:maps(`${x[1]} ${x[3]}`)}));
const materialDefinitions=[
  ['botanical','01','リミナルな植物園・温室','植物園・温室'],['science','02','地方の小さな科学系施設','科学系施設'],['aquarium','03','水族館・海中施設','水族館・海中施設'],['museums','04','博物館','博物館'],['mallcore','05','ドリームコア／モールコア','モールコア'],['tokyoPublic','06','東京のリミナルな公共空間','東京公共空間'],['libraries','07','空間に特徴のある図書館','図書館'],['municipal','08','自治体の面白いホームページ','自治体ウェブ資料'],['publicArchitecture','09','人が入れる公的建築施設','公的建築'],['rooftops','10','東京都内の入れる屋上・屋上庭園・公開テラス','屋上・屋上庭園'],['other','11','全国候補・その他','全国候補・その他'],['tully','12','病院内タリーズ','病院内タリーズ']
];
const materialItems=key=>key==='tully'?tullyItems:catalog[key];
const h=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sortableHead=`<thead><tr><th>参照</th><th><button class="sort-button" data-sort="prefecture" data-label="都道府県">都道府県 ↕</button></th><th>市区町村</th><th>店舗名・施設名</th><th><button class="sort-button" data-sort="type" data-label="分類">分類 ↕</button></th><th><button class="sort-button" data-sort="rank" data-label="評価">評価 ↕</button></th><th>説明・狙い目</th></tr></thead>`;
let facilitiesScrollTop=0;
function catalogSection(number,id,title,note,items){const rows=items.map(x=>`<tr data-prefecture="${h(x.prefecture)}" data-type="${h(x.type)}" data-rank="${h(x.rank)}"><td>${x.official?`<a href="${h(x.official)}" target="_blank" rel="noopener">公式</a> `:''}<a href="${h(x.maps)}" target="_blank" rel="noopener">地図</a></td><td>${h(x.prefecture)}</td><td>${h(x.city)}</td><td>${x.name==='玄海海中展望塔'?`<button class="facility-detail-link" data-facility-detail="genkai-undersea">${h(x.name)}</button>`:h(x.name)}</td><td>${h(x.type)}</td><td>${h(x.rank)}</td><td>${h(x.note)}</td></tr>`).join('');return `<section class="reference-section" id="${id}"><div class="reference-heading"><span>資料${number}</span><h2>${title}</h2><span>${String(items.length).padStart(3,'0')}件</span></div><p class="reference-note">${note}　都道府県・分類・評価の見出しで昇順／降順。</p><div class="record-table catalog-table"><table>${sortableHead}<tbody>${rows}</tbody></table></div></section>`}
function wireSortTables(){
  document.querySelectorAll('.record-table table').forEach(table=>{
    table.querySelectorAll('[data-sort]').forEach(button=>{
      button.onclick=()=>{
        const key=button.dataset.sort,ascending=button.dataset.direction!=='asc',body=table.tBodies[0],rows=[...body.rows],rank={S:0,A:1,B:2,C:3,'':4};
        rows.sort((a,b)=>{const av=a.dataset[key]||'',bv=b.dataset[key]||'';const value=key==='rank'?(rank[av]??9)-(rank[bv]??9):av.localeCompare(bv,'ja');return ascending?value:-value});
        rows.forEach(row=>body.append(row));
        table.querySelectorAll('[data-sort]').forEach(x=>{x.dataset.direction='';x.textContent=`${x.dataset.label} ↕`});
        button.dataset.direction=ascending?'asc':'desc';button.textContent=`${button.dataset.label} ${ascending?'↑':'↓'}`;
      };
    });
  });
}
function facilitiesPage(selectedKey=null,selectedIndex=null){
  active('facilities');
  const total=materialDefinitions.reduce((sum,[key])=>sum+materialItems(key).length,0);
  const jumps=materialDefinitions.map(([key,number,,short])=>`<button data-material-jump="${key}"><span>${number}</span> ${h(short)}</button>`).join('');
  const definition=materialDefinitions.find(x=>x[0]===selectedKey),selected=definition?materialItems(selectedKey)[Number(selectedIndex)]:null;
  const detail=selected?`<section class="material-detail facilities-top-detail"><div class="material-detail-copy"><div class="facility-record-head"><span>資料${definition[1]} / 個別記録</span><span>${selected.rank?`評価 ${h(selected.rank)}`:'分類・評価なし'}</span></div><h2>${h(selected.name)}</h2><div class="facility-register"><div><span>都道府県</span><span>${h(selected.prefecture)}</span></div><div><span>市区町村</span><span>${h(selected.city)}</span></div><div><span>分類</span><span>${h(selected.type)}</span></div><div><span>評価</span><span>${h(selected.rank)}</span></div><div class="facility-register-wide"><span>説明</span><span>${h(selected.note)}</span></div><div class="facility-register-wide"><span>参照</span><span>${selected.official?`<a href="${h(selected.official)}" target="_blank" rel="noopener">公式サイト</a>　`:''}<a href="${h(selected.maps)}" target="_blank" rel="noopener">地図</a>　<a href="${h(selected.maps)}" target="_blank" rel="noopener">Googleマップで写真を見る ↗</a></span></div></div></div><iframe title="${h(selected.name)}の地図" src="https://maps.google.com/maps?q=${encodeURIComponent(`${selected.name} ${selected.prefecture}${selected.city}`)}&output=embed" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></section>`:`<section class="material-detail facilities-top-detail"><div class="material-empty">施設資料 ${String(materialDefinitions.length).padStart(2,'0')}区分 / 全${String(total).padStart(3,'0')}件。店舗名・施設名を選択すると、この固定欄に資料データ詳細を表示します。</div><iframe title="日本のGoogleマップ" src="https://maps.google.com/maps?q=${encodeURIComponent('日本')}&output=embed" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></section>`;
  const sections=materialDefinitions.map(([key,number,title])=>{const items=materialItems(key),rows=items.map((x,index)=>`<tr class="${selected===x?'selected-row':''}" data-prefecture="${h(x.prefecture)}" data-type="${h(x.type)}" data-rank="${h(x.rank)}"><td>${x.official?`<a href="${h(x.official)}" target="_blank" rel="noopener">公式</a> `:''}<a href="${h(x.maps)}" target="_blank" rel="noopener">地図</a></td><td>${h(x.prefecture)}</td><td>${h(x.city)}</td><td><button class="facility-detail-link" data-all-facility="${key}/${index}">${h(x.name)}</button></td><td>${h(x.type)}</td><td>${h(x.rank)}</td><td>${h(x.note)}</td></tr>`).join('');return `<section class="all-material-section" id="material-${key}"><div class="reference-heading"><span>資料${number}</span><h2>${h(title)}</h2><span>${String(items.length).padStart(3,'0')}件</span></div><div class="record-table catalog-table"><table>${sortableHead}<tbody>${rows}</tbody></table></div></section>`}).join('');
  main.innerHTML=`<div class="facilities-ledger"><div class="facilities-ledger-fixed"><div class="facility-index-bar"><div class="facility-title-line"><h1>施設資料総合台帳</h1><nav class="material-jumps" aria-label="資料内リンク">${jumps}</nav></div><span>資料 ${String(materialDefinitions.length).padStart(2,'0')}</span><span>収録 ${String(total).padStart(3,'0')}</span><a href="https://www.google.com/maps" target="_blank" rel="noopener">Googleマップ ↗</a></div>${detail}</div><div class="facilities-ledger-scroll">${sections}</div></div>`;
  wire();wireSortTables();const ledgerScroll=document.querySelector('.facilities-ledger-scroll');ledgerScroll.scrollTop=facilitiesScrollTop;document.querySelectorAll('[data-material-jump]').forEach(e=>e.onclick=()=>{const target=document.querySelector('#material-'+e.dataset.materialJump);if(!target)return;facilitiesScrollTop=ledgerScroll.scrollTop+target.getBoundingClientRect().top-ledgerScroll.getBoundingClientRect().top;ledgerScroll.scrollTo({top:facilitiesScrollTop,behavior:'smooth'})});document.querySelectorAll('[data-all-facility]').forEach(e=>e.onclick=()=>{facilitiesScrollTop=ledgerScroll.scrollTop;go('facility/'+e.dataset.allFacility)});scrollTo(0,0)
}
function materialPage(key,selectedIndex=null){
  const definition=materialDefinitions.find(item=>item[0]===key);if(!definition)return facilitiesPage();
  active('facilities');
  const [,number,title]=definition,items=materialItems(key),selected=selectedIndex===null?null:items[Number(selectedIndex)];
  const detail=selected?`<section class="material-detail"><div class="material-detail-copy"><div class="facility-record-head"><span>資料${number} / 個別記録</span><span>${selected.rank?`評価 ${h(selected.rank)}`:'分類・評価なし'}</span></div><h2>${h(selected.name)}</h2><div class="facility-register"><div><span>都道府県</span><span>${h(selected.prefecture)}</span></div><div><span>市区町村</span><span>${h(selected.city)}</span></div><div><span>分類</span><span>${h(selected.type)}</span></div><div><span>評価</span><span>${h(selected.rank)}</span></div><div class="facility-register-wide"><span>説明</span><span>${h(selected.note)}</span></div><div class="facility-register-wide"><span>参照</span><span>${selected.official?`<a href="${h(selected.official)}" target="_blank" rel="noopener">公式サイト</a>　`:''}<a href="${h(selected.maps)}" target="_blank" rel="noopener">地図</a>　<a href="${h(selected.maps)}" target="_blank" rel="noopener">Googleマップで写真を見る ↗</a></span></div></div></div><iframe title="${h(selected.name)}の地図" src="https://maps.google.com/maps?q=${encodeURIComponent(`${selected.name} ${selected.prefecture}${selected.city}`)}&output=embed" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></section>`:`<div class="material-empty">店舗名・施設名を選択すると、施設情報・公式サイト・地図がここに表示されます。</div>`;
  const rows=items.map((x,index)=>`<tr class="${selected===x?'selected-row':''}" data-prefecture="${h(x.prefecture)}" data-type="${h(x.type)}" data-rank="${h(x.rank)}"><td>${x.official?`<a href="${h(x.official)}" target="_blank" rel="noopener">公式</a> `:''}<a href="${h(x.maps)}" target="_blank" rel="noopener">地図</a></td><td>${h(x.prefecture)}</td><td>${h(x.city)}</td><td><button class="facility-detail-link" data-facility-index="${index}">${h(x.name)}</button></td><td>${h(x.type)}</td><td>${h(x.rank)}</td><td>${h(x.note)}</td></tr>`).join('');
  main.innerHTML=`<div class="material-page"><div class="material-sticky"><div class="material-toolbar"><button class="text-button" data-route="facilities">← 資料目録</button><span>資料${number}</span><span>${String(items.length).padStart(3,'0')}件</span></div><h1>${h(title)}</h1>${detail}</div><div class="material-table-wrap record-table catalog-table ${selected?'has-detail':''}"><table>${sortableHead}<tbody>${rows}</tbody></table></div></div>`;
  wire();wireSortTables();document.querySelectorAll('[data-facility-index]').forEach(e=>e.onclick=()=>go(`facility/${key}/${e.dataset.facilityIndex}`));scrollTo(0,0)
}
function facilityDetail(key,index){facilitiesPage(key,index)}
function detail(id){
  const x=records.find(v=>v.id===id);if(!x)return home();active('');
  const gallery=x.gallery?.length?x.gallery:[x.image],related=records.filter(v=>v.id!==id&&v.tags.some(t=>x.tags.includes(t))).slice(0,3);
  main.innerHTML=`<article class="page detail"><button class="text-button back" data-route="archive">← 一覧へ戻る</button><div class="detail-copy detail-copy-top"><p class="eyebrow">${x.category} / ${x.date}</p><h1>${x.title}</h1><p class="intro">${x.excerpt}</p><div class="meta"><div><span>PLACE</span>${x.place}</div><div><span>FILE</span>${String(records.indexOf(x)+1).padStart(3,'0')} / ${String(records.length).padStart(3,'0')}</div></div><p class="body">${x.body}</p><div class="tag-cloud">${x.tags.map(t=>`<button class="chip" data-tag-link="${t}"># ${t}</button>`).join('')}</div></div><div class="gallery-workspace"><figure class="main-photo"><img id="main-photo" src="${gallery[0]}" alt="${x.title} メイン写真"><figcaption>PHOTO 01 / ${String(gallery.length).padStart(2,'0')}</figcaption></figure><div class="photo-grid">${gallery.map((src,i)=>`<button class="photo-tile ${i===0?'active':''}" data-photo="${src}" data-photo-index="${i}" aria-label="写真${i+1}を表示"><img src="${src}" alt="${x.title} 別角度 ${i+1}" loading="lazy"><span>${String(i+1).padStart(2,'0')}</span></button>`).join('')}</div></div>${related.length?`<section class="related"><div class="section-head"><h2>近くの記録</h2></div><div class="grid">${related.map(card).join('')}</div></section>`:''}</article>`;
  wire();
  document.querySelectorAll('[data-photo]').forEach(e=>e.onclick=()=>{document.querySelector('#main-photo').src=e.dataset.photo;document.querySelector('.main-photo figcaption').textContent=`PHOTO ${String(Number(e.dataset.photoIndex)+1).padStart(2,'0')} / ${String(gallery.length).padStart(2,'0')}`;document.querySelectorAll('[data-photo]').forEach(t=>t.classList.toggle('active',t===e));});
  document.querySelectorAll('[data-tag-link]').forEach(e=>e.onclick=()=>{go('tags');setTimeout(()=>document.querySelector(`[data-tag="${e.dataset.tagLink}"]`)?.click())});scrollTo(0,0)
}
function route(){const routeHash=location.hash.slice(1)||'facilities',parts=routeHash.split('/');routeHash.startsWith('facility/')?facilityDetail(parts[1],parts[2]):routeHash.startsWith('material/')?materialPage(parts[1]):facilitiesPage()}function search(){const s=q.value.trim().toLowerCase(),hits=s?records.filter(x=>[x.title,x.category,x.place,x.excerpt,x.body,...x.tags].join(' ').toLowerCase().includes(s)):records.slice(0,4);results.innerHTML=hits.length?hits.map(x=>`<button class="hit" data-hit="${x.id}"><img src="${x.image}" alt=""><span><strong>${x.title}</strong><br><small>${x.category} · ${x.date}</small></span></button>`).join(''):'<p class="empty">該当する記録はありません。</p>';document.querySelectorAll('[data-hit]').forEach(e=>e.onclick=()=>{dialog.close();go('detail/'+e.dataset.hit)})}
document.querySelector('#open-search').onclick=()=>{dialog.showModal();search();setTimeout(()=>q.focus(),50)};document.querySelector('#close-search').onclick=()=>dialog.close();q.oninput=search;addEventListener('hashchange',route);wire();route();
