/* Optional English labels. Data fields remain shared; missing entries fall back to Japanese. */
window.EN_TRANSLATIONS={
  materials:{
    '東京の植物園':'Tokyo Botanical Gardens','東京の科学館':'Tokyo Science Museums','博物館':'Museums','天文台・プラネタリウム':'Observatories & Planetariums','遊園地・レジャー施設':'Amusement & Leisure Facilities','単一テーマ博物館':'Single-Theme Museums','こども向け施設':'Children’s Facilities','地方の科学館':'Regional Science Museums','地方の植物園':'Regional Botanical Gardens','東京の企業博物館':'Corporate Museums in Tokyo','企業・産業系ライブラリー':'Corporate & Industry Libraries','企業・大学の一般開放空間':'Open Corporate & University Spaces','一般開放された企業・大学・財団空間':'Open Corporate, University & Foundation Spaces','アトリウム・屋内公開空地':'Atria & Indoor Public Spaces','用途転換された歴史的建築':'Adaptive Reuse of Historic Buildings','用途転換された公園':'Parks with Transformed Uses','古いビル':'Older Buildings','戦後闇市・マーケットの痕跡':'Traces of Postwar Black Markets','大型レジャー施設':'Large Leisure Facilities','空間に特徴のある図書館':'Libraries with Distinctive Spaces','東京歴建（東京都選定歴史的建造物）':'Tokyo Historic Buildings','元○○だった東京のホテル':'Tokyo Hotels with Earlier Uses','VR・3Dで歩ける場所':'Places Walkable in VR & 3D','カプセルホテル':'Capsule Hotels','フェリー・旅客船ターミナル':'Ferry & Passenger Ship Terminals','レトロゲームセンター':'Retro Arcades','レトロ自販機':'Retro Vending Machines','人が入れる公的建築施設':'Public Buildings Open to Visitors','公共施設・文化施設内の食堂':'Cafeterias in Public & Cultural Facilities','公的防災関連施設':'Public Disaster-Prevention Facilities','古いイオン':'Older AEON Stores','名建築で昼食を':'Lunch in Notable Buildings','団地商店街':'Housing-Complex Shopping Streets','地下街・地下道':'Underground Malls & Passages','地域文化施設':'Local Cultural Facilities','地域独自スーパー':'Regional Supermarkets','大型リゾート施設':'Large Resort Facilities','展望塔・展望施設':'Observation Towers & Viewpoints','工場・製造現場見学':'Factory & Production-Site Tours','廃校活用施設':'Repurposed School Facilities','役所・庁舎の市民開放空間':'Public Spaces in Government Offices','旧世代型商業施設':'Legacy-Format Commercial Facilities','時間が残る鉄道駅':'Railway Stations Where Time Remains','東京の区民ホール・公共ホール':'Tokyo Ward & Public Halls','東京の失われた名所':'Lost Landmarks of Tokyo','東京都内の入れる屋上・屋上庭園・公開テラス':'Accessible Rooftops, Rooftop Gardens & Public Terraces in Tokyo','東京都内の戦争史・戦争遺構を歩く':'Walking Tokyo’s War History & Relics','東京都内の病院内タリーズ':'Tully’s Cafés Inside Tokyo Hospitals','水族館・海中施設':'Aquariums & Undersea Facilities','生物展示施設':'Living-Organism Exhibits','目的地化した店舗':'Destination Stores','社会科見学施設':'Educational Field-Trip Facilities','空港ターミナル':'Airport Terminals'
  },
  facilities:{
    '三井住友海上 駿河台緑地・屋上庭園':'MS&AD Surugadai Greenery & Rooftop Garden','田町トーセイビル 公開空地':'Tamachi Tosei Building Public Plaza','丸紅「紅の杜」':'Marubeni “Kurenai no Mori”','鉄鋼ビルディング 西側緑地・散策路':'Tekko Building West Greenway','大手町タワー「大手町の森」':'Otemachi Forest at Otemachi Tower','アークヒルズ サウスタワー 屋上庭園スカイパーク':'Ark Hills South Tower Sky Park','平河町森タワー 公開空地':'Hirakawacho Mori Tower Public Space','日本紙パルプ商事フォアフロントタワー周辺公開空間':'Japan Pulp & Paper Forefront Tower Open Space','住友不動産青葉台タワー 公開空地':'Sumitomo Realty Aobadai Tower Public Space','三菱商事「231 PLACE / 231 GALLERY」':'Mitsubishi Corporation 231 PLACE / 231 GALLERY','第一生命ロビー':'Dai-ichi Life Lobby','法政大学 市ケ谷キャンパス屋上緑化スペース':'Hosei University Ichigaya Rooftop Green Space'
  }
};
